#!/bin/bash

DATA=/data
SRV_NAME=xxx-proxy
SRV_PATH=$DATA/$SRV_NAME
LIB_PATH=$SRV_PATH/lib
OPBIN_PATH=$SRV_PATH/opbin

VERSION=1.0.0
VTYPE=SNAPSHOT

SPI_VERSION=1.14.0

#FILENAME=xxx-$SRVNAME-$VERSION-$VTYPE
SPI_FILE=spi-$SPI_VERSION-$VTYPE.jar
SPI_FILE_BAK=$SPI_FILE.bak

#TAR_FILENAME=$FILENAME-assembly.tar.gz

echo 'sh $OPBIN_PATH/stop.sh'
#backup old spi
echo "mv $LIB_PATH/$SPI_FILE $LIB_PATH/$SPI_FILE_BAK"
mv $LIB_PATH/$SPI_FILE $LIB_PATH/$SPI_FILE_BAK
echo "cp $DATA/$SPI_FILE $LIB_PATH/$SPI_FILE"
cp $DATA/$SPI_FILE $LIB_PATH/$SPI_FILE

echo 'sh $OPBIN_PATH/start.sh'
#sh $OPBIN_PATH/start.sh
