#!/bin/bash

INPUT_HOST=$1
METHOD=$2
FILE=$3

USR=root
#bj
HOST135=10.185.234.135
#xj
HOST224=10.185.3.224
HOST238=10.185.3.238
HOST239=10.185.3.239
HOST245=10.185.3.245
HOST246=10.185.3.246
HOST64=10.185.2.64
HOST70=10.185.2.70
#default host
HOST=$HOST135
UPPATH=/opt/upload/

if [ $# -lt 3 ]; then
        echo 'SCP must have three parameter!'
        exit
fi

if [ "$INPUT_HOST" == "135" ]; then
	HOST=$HOST135
elif [ "$INPUT_HOST" == "224" ]; then
	HOST=$HOST224
elif [ "$INPUT_HOST" == "238" ]; then
        HOST=$HOST238
elif [ "$INPUT_HOST" == "239" ]; then
        HOST=$HOST239
elif [ "$INPUT_HOST" == "245" ]; then
        HOST=$HOST245
elif [ "$INPUT_HOST" == "246" ]; then
        HOST=$HOST246
elif [ "$INPUT_HOST" == "64" ]; then
        HOST=$HOST64
elif [ "$INPUT_HOST" == "70" ]; then
        HOST=$HOST70
fi

echo "Host $HOST"

if [ "$METHOD" == "put" ]; then
	echo "scp $FILE $USR@$HOST:$UPPATH$FILE"
	scp $FILE $USR@$HOST:$UPPATH$FILE
elif [ "$METHOD" == "get" ]; then
	echo "scp $USR@$HOST:$UPPATH$FILE" $FILE
	scp $USR@$HOST:$UPPATH$FILE $FILE
fi
